name: Build Android APK from config.json

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read config.json
        id: config
        run: |
          CONFIG_FILE=config.json
          if [ ! -f "$CONFIG_FILE" ]; then
            echo "config.json موجود نیست!"
            exit 1
          fi
          TEXT_VIEW=$(jq -r '.text_view' $CONFIG_FILE)
          APP_NAME=$(jq -r '.app_name' $CONFIG_FILE)
          APK_NAME=$(jq -r '.apk_name' $CONFIG_FILE)
          PACKAGE_NAME=$(jq -r '.package_name' $CONFIG_FILE)
          echo "TEXT_VIEW=$TEXT_VIEW" >> $GITHUB_ENV
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
          echo "APK_NAME=$APK_NAME" >> $GITHUB_ENV
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV

      - name: Create minimal Android project
        run: |
          mkdir -p MyApp/app/src/main/java/com/example/
          mkdir -p MyApp/app/src/main/res/layout
          
          # MainActivity.java با TextView
          echo "package com.example;
          import android.os.Bundle;
          import android.widget.TextView;
          import androidx.appcompat.app.AppCompatActivity;
          public class MainActivity extends AppCompatActivity {
              @Override
              protected void onCreate(Bundle savedInstanceState) {
                  super.onCreate(savedInstanceState);
                  TextView tv = new TextView(this);
                  tv.setText(\"$TEXT_VIEW\");
                  tv.setTextSize(24);
                  setContentView(tv);
              }
          }" > MyApp/app/src/main/java/com/example/MainActivity.java

          # AndroidManifest.xml
          echo "<manifest package=\"$PACKAGE_NAME\" xmlns:android=\"http://schemas.android.com/apk/res/android\">
            <application android:label=\"$APP_NAME\">
              <activity android:name=\".MainActivity\">
                <intent-filter>
                  <action android:name=\"android.intent.action.MAIN\" />
                  <category android:name=\"android.intent.category.LAUNCHER\" />
                </intent-filter>
              </activity>
            </application>
          </manifest>" > MyApp/app/src/main/AndroidManifest.xml

          # build.gradle ساده
          echo "plugins { id 'com.android.application' }
          android {
              compileSdk 33
              defaultConfig {
                  applicationId \"$PACKAGE_NAME\"
                  minSdk 21
                  targetSdk 33
                  versionCode 1
                  versionName \"1.0\"
              }
          }" > MyApp/app/build.gradle

      - name: Build APK (Simulation)
        run: |
          mkdir -p output
          touch output/$APK_NAME   # شبیه‌سازی خروجی APK

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: output/$APK_NAME
