name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Read config.json
        id: config
        run: |
          if [ ! -f "config.json" ]; then
            echo "config.json موجود نیست!"
            exit 1
          fi
          TEXT_VIEW=$(jq -r '.text_view' config.json)
          APP_NAME=$(jq -r '.app_name' config.json)
          APK_NAME=$(jq -r '.apk_name' config.json)
          PACKAGE_NAME=$(jq -r '.package_name' config.json)
          echo "TEXT_VIEW=$TEXT_VIEW" >> $GITHUB_ENV
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
          echo "APK_NAME=$APK_NAME" >> $GITHUB_ENV
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV

      - name: Update MainActivity with TextView
        run: |
          echo "package com.example;
          import android.os.Bundle;
          import android.widget.TextView;
          import androidx.appcompat.app.AppCompatActivity;
          public class MainActivity extends AppCompatActivity {
              @Override
              protected void onCreate(Bundle savedInstanceState) {
                  super.onCreate(savedInstanceState);
                  TextView tv = new TextView(this);
                  tv.setText(\"$TEXT_VIEW\");
                  tv.setTextSize(24);
                  setContentView(tv);
              }
          }" > app/src/main/java/com/example/MainActivity.java

      - name: Update AndroidManifest.xml
        run: |
          echo "<manifest package=\"$PACKAGE_NAME\" xmlns:android=\"http://schemas.android.com/apk/res/android\">
            <application android:label=\"$APP_NAME\">
              <activity android:name=\".MainActivity\">
                <intent-filter>
                  <action android:name=\"android.intent.action.MAIN\" />
                  <category android:name=\"android.intent.category.LAUNCHER\" />
                </intent-filter>
              </activity>
            </application>
          </manifest>" > app/src/main/AndroidManifest.xml

      - name: Build APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk
